Docker pull
appscode/analytics pull request #7
Opened 2017-08-11 09:49 UTC by the-redback

> $ analytics run 
This command saves the pull logs in below files,
 
1. https://hub.docker.com/v2/repositories/appscode/?page_size=100 => https://docs.google.com/spreadsheets/d/18lNbYqiP4gsKBoLDoUw2ejOGWN3t3mUOyKGaKeye3kI/edit#gid=1034833628

 2. https://hub.docker.com/v2/repositories/kubedb/?page_size=100 => https://docs.google.com/spreadsheets/d/10OGrTJxEDox4VR15U7HPGRjiFpTNfhiUGMuL7BQJKJU/edit#gid=1878783245

2017-08-11 10:07 UTC, sanjid133 reviewed
SpreadSheetIdKubeDB and SpreadSheetIdAppsCode  can be read from env variable or file

2017-08-11 10:31 UTC, sadlil requested changes

2017-08-11 10:31 UTC, sadlil commented on pkg/docker/docker_api.go
> +package docker_api
package name should match with directory structure. use `package docker`.
- if you want package name as `dockerapi` not `docker_api`

2017-08-11 10:31 UTC, sadlil commented on pkg/docker/docker_api.go
> +	Previous interface{} `json:"previous"`
`Next` and `Previous` should *string
As
```json
{
  "count": 93,
  "next": "https://hub.docker.com/v2/repositories/appscode/?page=3&page_size=5",
  "previous": "https://hub.docker.com/v2/repositories/appscode/?page=1&page_size=5"
}

// When there is no page available
{
  "count": 93,
  "next": null,
  "previous": null
}
```

we should get data until `Next = nil`

2017-08-11 10:31 UTC, sadlil commented on pkg/docker/docker_api.go
> +
If we are going to stay with google docs now, at least make them as flags or EnvVar

2017-08-11 10:31 UTC, sadlil commented on pkg/docker/docker_api.go
> +
why those blank lines. remove unnecessary blank lines.

2017-08-11 10:31 UTC, sadlil commented on pkg/docker/docker_api.go
> +	if err != nil {
You should be careful about `Next` page of response.

2017-08-11 10:31 UTC, sadlil commented on pkg/docker/docker_api.go
> +	time.Sleep(5 * time.Second)
time.Sleep doesn't make it slow.
if you are careful about rate limit, then you should call this method when ever it is ok to call.
like call this method every 5 seconds and update data.

2017-08-11 10:31 UTC, sadlil commented on pkg/docker/docker_api.go
> +
remove the previous repetation. move them to a separate method or function and use them as where necessary.

2017-08-16 08:31 UTC, tamalsaha commented on pkg/cmds/server.go
> +			c.AddFunc("@every 4h", dockerapi.DockerAnalytics)
c.AddFunc("@every 4h", func(){
	if err := dockerapi.DockerAnalytics(); err != nil {
		log.Errorln(err)
	}
})

2017-08-16 20:43 UTC, merged